config/routes.rb
Merchant::Application.routes.draw do

  match '/auth/:provider/callback', to: 'sessions#create', via: :get
  
  match "/login" => redirect("/auth/twitter"), as: :login, via: :get

  match "/logout" => "sessions#destroy", as: :logout, via: :get
  
  resources :orders

  resources :order_items

  resources :products

  root to: "products#index"

  

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  belongs_to :user

  def total
    total = 0
    order_items.each do |item|
      total += item.subtotal
    end
    return total
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def edit
  end

  def index
    @orders = Order.all
  end

  def create
    @order_item = @order.order_items.new(quantity: 1, product_id: params[:product_id])
    
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Successfully added product to cart.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    
  def set_order
    @order = Order.find(params[:id])
  end

  def load_order
    @order = Order.find_or_initialize_by_id(session[:order_id], status: "unsubmitted")
    if @order.new_record?
      @order.save!
      session[:order_id] = @order.id
    end 
  end

  def order_params
    params.require(:order).permit(:user_id, :status, :quantity)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user_id %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %><br/>
<%= link_to 'Back', products_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h1>Your Order</h1>

<table>
  <tr>
    <th>Customer</th>
    <td><%= @order.user.name if @order.user %></td>
  </tr>
  <tr>
    <th>Status:</th>
    <td><%= @order.status %></td>
  </tr>
  <tr>
    <th>Items:</th>
    <td><%= @order.order_items.count %></td>
  </tr>
  <tr>
    <th>Items</th>
    <th>Title</th>
    <th>Quantity</th>
    <th>Stock</th>
    <th>Unit Price</th>
    <th>Subtotal</th>
    
  </tr>
  <% @order.order_items.each do |order_item| %>
  <tr>
  	<td><%= image_tag "products/#{order_item.product.image_url}" %></td>

  	<td><%= order_item.product.title %></br>
    <%= link_to 'Remove', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 
  	<td><%= link_to order_item.quantity, edit_order_item_path(order_item) %></td>

    <td><%= print_stock order_item.product.stock, order_item.quantity %></td>
  

  	<td><%= print_price order_item.product.price %></td>

  	<td><%= print_price order_item.subtotal %></td>
   
  </tr>
<% end %>

<td></td>
<td></td>
<td></td>
<th>Total :</th>
<td><%= print_price @order.total %></td>
</table>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>
<%= link_to "Empty Cart", @order, data: { confirm: 'Are you sure?' }, method: :delete %>